name: Setup environment

on:
  workflow_call:
    inputs:
      DOCKER_HUB_USERNAME:
        required: true
        type: string
      DOCKER_HUB_PAT:
        required: true
        type: string
      GCP_SERVICE_ACCOUNT_CREDENTIALS:
        required: true
        type: string
      GCP_PROJECT_ID:
        required: true
        type: string

runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.DOCKER_HUB_USERNAME }}
        password: ${{ inputs.DOCKER_HUB_PAT }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.GCP_SERVICE_ACCOUNT_CREDENTIALS }}

    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ inputs.GCP_PROJECT_ID }}

    - name: Configure Terraform
      uses: hashicorp/setup-terraform@v3
