services:
  rabbitmq:
    build: ./packages/rabbitmq
    hostname: rmq
    container_name: rmq
    expose:
      - 5552
      - 5672
    ports:
      - 15672:15672 
    healthcheck:
      test: [CMD, rabbitmq-diagnostics, -q, ping]
      interval: 30s
      timeout: 10s
      retries: 5

  scraper_scheduler:
    build: ./packages/scraper_scheduler
    hostname: scraper_scheduler
    container_name: scraper_scheduler
    expose:
      - 7000
    ports:
      - 7000:7000
    environment:
      - HOST_ADDR=0.0.0.0:7000
      - OUTPUT_ADDR=item_scraper:6800

  item_scraper:
    build: ./packages/item_scraper
    hostname: item_scraper
    container_name: item_scraper
    expose:
      - 6800
    ports:
      - 6800:6800
    environment:
      - RABBITMQ_HOST=rmq
      - RABBITMQ_STREAM_PORT=5552
      - RABBITMQ_AMQP_PORT=5672
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  default:
    name: scraper-network