import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import { createClient } from '@supabase/supabase-js';
var app = createApp(App);
var supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
var supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
export var supabase = createClient(supabaseUrl, supabaseAnonKey);
app.provide('supabase', supabase);
app.use(router);
app.mount('#app');
