name: Deploy Monolith

on:
  workflow_call:
    inputs:
      commit_sha:
        required: true
        type: string
    secrets:
      ANTHROPIC_API_KEY:
        required: true
      OPENAI_API_KEY:
        required: true
      DATABASE_URL:
        required: true
      JWT_SECRET:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init -backend-config=backend.conf

      - name: Validate Terraform configuration
        working-directory: ./terraform
        run: terraform validate

      - name: Create env vars JSON
        working-directory: ./terraform
        run: |
          cat > backend_env.tfvars.json << EOF
          {
            "backend_env_vars": {
              "PORT": "8080",
              "ANTHROPIC_API_ENDPOINT": "https://api.anthropic.com/v1/messages",
              "ANTHROPIC_API_KEY": "${{ secrets.ANTHROPIC_API_KEY }}",
              "ANTHROPIC_MODEL": "claude-3-5-sonnet-20241022",
              "ANTHROPIC_VERSION": "2023-06-01",
              "OPENAI_API_ENDPOINT": "https://api.openai.com/v1/chat/completions",
              "OPENAI_API_KEY": "${{ secrets.OPENAI_API_KEY }}",
              "OPENAI_MODEL": "gpt-4o-mini",
              "EMBEDDER_ENDPOINT": "https://embedder.itemtracker.hish.dev",
              "RUST_LOG": "DEBUG",
              "DATABASE_URL": "${{ secrets.DATABASE_URL }}",
              "JWT_SECRET": "${{ secrets.JWT_SECRET }}"
            }
          }
          EOF

      - name: Apply infrastructure changes
        working-directory: ./terraform
        run: terraform apply -auto-approve \
          -target=google_cloud_run_service.backend \
          -var="backend_image_tag=${{ inputs.commit_sha }}" \
          -var="embedder_image_tag=${{ inputs.commit_sha }}" \
          -var-file=backend_env.tfvars.json
