[package]
name = "monolith"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "^1.40.0", features = ["full"] }
serde = { version = "^1.0.210", features = ["derive"] }
reqwest = { version = "^0.12.8", features = ["json", "multipart"] }
axum = "^0.7.7"
axum-extra = { version = "0.10.1", features = ["typed-header"] }
uuid = { version = "^1.11.0", features = ["serde"] }
chrono = { version = "^0.4.38", features = ["serde"] }
tracing = "^0.1.40"
tracing-subscriber = { version = "^0.3.18", features = ["env-filter", "fmt"] }
tokio-cron-scheduler = { version = "^0.13.0", features = ["signal"] }
croner = "^2.0.6"
thiserror = "1.0.65"
reqwest-middleware = "0.3.3"
futures = "0.3.31"
dotenv = "0.15.0"
serde_json = "1.0.133"
image = "0.25.5"
base64 = "0.22.1"
p256 = "0.13.2"
rand = "0.9.0"
jsonwebtoken = "9.3.1"
redis = { version = "0.29.0", features = ["tokio-comp", "json"] }

# DB related
diesel-async = { version = "0.5.2", features = ["postgres", "deadpool"] }
diesel = { version = "2.2.9", features = ["postgres_backend", "serde_json", "chrono", "uuid"] }
scoped-futures = "0.1.4"
once_cell = "1.21.3"

