[package]
name = "scraper_scheduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "^1.40.0", features = ["full"] }
serde = { version = "^1.0.210", features = ["derive"] }
reqwest = { version = "^0.12.8", features = ["json"] }
axum = "^0.7.7"
uuid = "^1.11.0"
chrono = { version = "^0.4.38", features = ["serde"] }
tracing = "^0.1.40"
tracing-subscriber = { version = "^0.3.18", features = ["env-filter"] }
tokio-cron-scheduler = { version = "^0.13.0", features = ["signal"] }
croner = "^2.0.6"
thiserror = "1.0.65"
reqwest-middleware = "0.3.3"
futures = "0.3.31"
dotenv = "0.15.0"
