name: Deploy backend/monolith

inputs:
  commit_sha:
    required: true
    type: string
  DOCKER_HUB_USERNAME:
    required: true
    type: string
  DOCKER_HUB_PAT:
    required: true
    type: string
  GCP_SERVICE_ACCOUNT_CREDENTIALS:
    required: true
    type: string
  GCP_PROJECT_ID:
    required: true
    type: string
  ANTHROPIC_API_KEY:
    required: true
    type: string
  OPENAI_API_KEY:
    required: true
    type: string
  DATABASE_URL:
    required: true
    type: string
  JWT_SECRET:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.DOCKER_HUB_USERNAME }}
        password: ${{ inputs.DOCKER_HUB_PAT }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.GCP_SERVICE_ACCOUNT_CREDENTIALS }}

    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ inputs.GCP_PROJECT_ID }}

    - name: Configure Terraform
      uses: hashicorp/setup-terraform@v3  

    - name: Initialize Terraform
      working-directory: ./terraform
      shell: bash
      run: terraform init -backend-config=backend.conf

    - name: Validate Terraform configuration
      working-directory: ./terraform
      shell: bash
      run: terraform validate

    - name: Create env vars JSON
      working-directory: ./terraform
      shell: bash
      run: |
        cat > backend_env.tfvars.json << EOF
        {
          "backend_env_vars": {
            "PORT": "8080",
            "ANTHROPIC_API_ENDPOINT": "https://api.anthropic.com/v1/messages",
            "ANTHROPIC_API_KEY": "${{ inputs.ANTHROPIC_API_KEY }}",
            "ANTHROPIC_MODEL": "claude-3-5-sonnet-20241022",
            "ANTHROPIC_VERSION": "2023-06-01",
            "OPENAI_API_ENDPOINT": "https://api.openai.com/v1/chat/completions",
            "OPENAI_API_KEY": "${{ inputs.OPENAI_API_KEY }}",
            "OPENAI_MODEL": "gpt-4o-mini",
            "EMBEDDER_ENDPOINT": "https://embedder.itemtracker.hish.dev",
            "RUST_LOG": "DEBUG",
            "DATABASE_URL": "${{ inputs.DATABASE_URL }}",
            "JWT_SECRET": "${{ inputs.JWT_SECRET }}"
          }
        }
        EOF

    - name: Apply infrastructure changes
      working-directory: ./terraform
      shell: bash
      run: terraform apply -auto-approve -target=google_cloud_run_service.backend -var="backend_image_tag=${{ inputs.commit_sha }}" -var-file=backend_env.tfvars.json
