name: Backend/monolith deployment

on:
  push:
    paths:
      - 'packages/monolith/**'
  pull_request:
    paths:
      - 'packages/monolith/**'
  workflow_dispatch:

jobs:
  check:
    name: Cargo Check
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: Check project
        working-directory: ./packages/monolith
        run: cargo check
      
      - name: Build image
        working-directory: ./packages/monolith
        run: docker build -t monolith:test .