name: Backend/monolith deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/monolith/**'
  workflow_dispatch:

jobs:
  check:
    name: Check and build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: Check project
        working-directory: ./packages/monolith
        run: cargo check
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
        
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      
      - name: Build and push image
        working-directory: ./packages/monolith
        run: 
          docker build -t mhish/itemtracker_monolith:${{ github.sha }} .
          docker images mhish/itemtracker_monolith:${{ github.sha }}
          docker image push mhish/itemtracker_embedder:${{ github.sha }}
      
      - name: 