name: Backend/monolith deployment
on:
  push:
    branches: [ main ]
    paths:
      - 'packages/monolith/**'
  workflow_dispatch:
jobs:
  setup:
    name: Setup environment
    runs-on: ubuntu-latest
    outputs:
      setup_done: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PAT: ${{ secrets.DOCKER_HUB_PAT }}
          GCP_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
            
  check_image:
    name: Check for existing image
    runs-on: ubuntu-latest
    needs: [setup]
    outputs:
      image_exists: ${{ steps.check_image.outputs.exists }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: Check if image already exists
        id: check_image
        run: |
          if docker manifest inspect mhish/itemtracker_monolith:${{ github.sha }} > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    needs: [check_image, setup]
    if: needs.check_image.outputs.image_exists == 'false'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/backend/build-push
        with:
          commit_sha: ${{ github.sha }}
  deploy:
    name: Deploy service
    runs-on: ubuntu-latest
    needs: [check_image, build, setup]
    if: always() && (needs.check_image.outputs.image_exists == 'true' || needs.build.result == 'success')
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/backend/deploy
        with:
          commit_sha: ${{ github.sha }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}