name: Embedder deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/embedder/**'
  workflow_dispatch:

jobs:
  check:
    name: Check and build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Build image
        working-directory: ./packages/embedder
        run: docker build -t embedder:latest .