name: Embedder deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/embedder/**'
  workflow_dispatch:

jobs:
  check:
    name: Check and build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      
      - name: Build and push image
        working-directory: ./packages/embedder
        run: 
          docker build -t mhish/itemtracker_embedder:${{ github.sha }} .
          docker images mhish/itemtracker_embedder:${{ github.sha }}
          docker image push mhish/itemtracker_embedder:${{ github.sha }}

      - name: Apply Terraform
          